# This is a basic workflow to help you get started with Actions

name: pages

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt install -y wget git
        wget -q -O - \
        "https://github.com/getzola/zola/releases/download/v0.14.1/zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin
        
        git config --global url."https://".insteadOf git://
        git config --global url."https://github.com/".insteadOf git@github.com:
        git submodule update --init --recursive
        remote_repo="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch=master
        
        zola build
        cd public
        touch .nojekyll
        git init
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .

        git commit -m "Deploy GitHub Pages"
        git push --force "${remote_repo}" master:${remote_branch}
